name: Retriever

on:
  schedule:
    - cron: "0 * * * *" # cf. https://crontab.guru/examples.html
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: '3.7'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Retriever
        run: python retrieve_data.py
      - name: Print time
        run: |
          echo "$(python -c 'import datetime as dt; print(dt.datetime.now().__str__())')"
      - name: Commit and push if it changed
        run: |
          git config user.name actions-user
          git config user.email "actions@github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "GH ACTION latest update: ${timestamp}" || exit 0
          git push